import { StyleSheet, Platform } from "react-native";
import {
  SPACING,
  normalizeSize,
  shadowSoft,
  R,
  GLASS,
  ACCENT,
  S,
} from "./challengeDetails.tokens";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  duoPendingVsPillV2: {
  paddingHorizontal: 10,
  paddingVertical: 4,
  borderRadius: 999,
  minWidth: 44,
  alignItems: "center",
  justifyContent: "center",
  zIndex: 6,
  elevation: 6,
  overflow: "visible",
  backgroundColor: "rgba(255,215,0,0.22)",
  borderWidth: StyleSheet.hairlineWidth,
  borderColor: "rgba(255,215,0,0.30)",
},
duoPendingVsTextV2: {
  fontFamily: "Comfortaa_700Bold",
  fontSize: 12,
  letterSpacing: 1,
  color: "#111",
},
  duoPendingRingV2: {
  position: "absolute",
  width: 56,
  height: 56,
  borderRadius: 56,
  borderWidth: 1,
  borderColor: "rgba(255,159,28,0.30)", 
},
duoPendingGlowV2: {
  position: "absolute",
  width: 18,
  height: 18,
  borderRadius: 18,
  backgroundColor: "rgba(255,159,28,0.14)", 
},
duoPendingDotV2: {
  position: "absolute",
  width: 18,
  height: 18,
  borderRadius: 18,
  borderWidth: 1,
  borderColor: "rgba(255,215,0,0.38)",
},
duoPendingDotCoreV2: {
  width: 7,
  height: 7,
  borderRadius: 7,
  backgroundColor: "rgba(255,215,0,0.92)",
},
warmupToastWrap: {
  position: "absolute",
  left: 14,
  right: 14,
  zIndex: 99999,
  elevation: 999,
},
warmupToastBlur: {
  borderRadius: 18,
  overflow: "hidden",
},
warmupToastInner: {
  borderRadius: 18,
  paddingVertical: 12,
  paddingHorizontal: 12,
  flexDirection: "row",
  alignItems: "center",
  gap: 10,
},
warmupToastStroke: {
  ...StyleSheet.absoluteFillObject,
  borderRadius: 18,
  borderWidth: StyleSheet.hairlineWidth,
  borderColor: "rgba(255,255,255,0.16)",
},
warmupToastIconPill: {
  width: 28,
  height: 28,
  borderRadius: 10,
  overflow: "hidden",
  alignItems: "center",
  justifyContent: "center",
},
warmupToastTitle: {
  fontFamily: "Comfortaa_700Bold",
  fontSize: 13.6,
  lineHeight: 16,
},
warmupToastSub: {
  marginTop: 2,
  fontFamily: "Comfortaa_400Regular",
  fontSize: 12.2,
  lineHeight: 15,
},
duoPendingShell: {
  marginTop: 14,
  width: "100%",
},
duoPendingCardV2: {
  borderRadius: 22,
  padding: 14,
  overflow: "hidden",
  borderWidth: StyleSheet.hairlineWidth,
  borderColor: "rgba(255,255,255,0.10)",
  ...shadowSoft,
},
duoBattleHeaderWrap: {
  width: "100%",
  maxWidth: 560,
  alignSelf: "center",
  marginTop: 14,
  marginBottom: 8,
  paddingHorizontal: 6,
},
duoBattleTitleRow: {
  width: "100%",
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 10,
  paddingVertical: 8,
  paddingHorizontal: 12,
  borderRadius: 14,
  backgroundColor: Platform.select({
    ios: "rgba(0,0,0,0.28)",
    android: "rgba(0,0,0,0.22)",
    default: "rgba(0,0,0,0.26)",
  }) as any,
  borderWidth: StyleSheet.hairlineWidth,
  borderColor: "rgba(255,255,255,0.16)",
  zIndex: 2,
  elevation: 2,
},
duoBattleTitle: {
  flexShrink: 1,
  minWidth: 0,
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(12.6),
  letterSpacing: 1.2,
  color: "rgba(255,255,255,0.94)",
  includeFontPadding: false,
  ...(Platform.OS === "ios"
    ? {
        textShadowColor: "rgba(0,0,0,0.55)",
        textShadowRadius: 6,
        textShadowOffset: { width: 0, height: 1 },
      }
    : {}),
},
duoBattleMini: {
  flexShrink: 0,
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(11.2),
  color: "rgba(255,255,255,0.78)",
  includeFontPadding: false,
},
duoBattleBarWrap: {
  width: "100%",
  maxWidth: 560,
  alignSelf: "center",
  marginTop: 0,
  opacity: 1,
},
duoPendingStrokeV2: {
  ...StyleSheet.absoluteFillObject,
  borderRadius: 22,
  borderWidth: StyleSheet.hairlineWidth,
  borderColor: "rgba(255,255,255,0.14)",
  opacity: 0.9,
},
duoPendingSheenV2: {
  position: "absolute",
  left: -40,
  top: -60,
  width: 160,
  height: 160,
  borderRadius: 160,
  backgroundColor: "rgba(255,255,255,0.08)",
  transform: [{ rotate: "18deg" }],
},
duoPendingTopRowV2: {
  flexDirection: "row",
  alignItems: "center",
  marginBottom: 10,
},
duoPendingDotWrapV2: {
  width: 18,
  height: 18,
  marginRight: 10,
  alignItems: "center",
  justifyContent: "center",
},
duoPendingTopTextV2: {
  flex: 1,
  minWidth: 0,
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(12.5),
  letterSpacing: 0.3,
},
duoPendingTopRightV2: {
  width: 22,
  alignItems: "flex-end",
},
duoPendingCenterV2: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  marginBottom: 10,
},
duoPendingAvatarColV2: {
  width: "40%",
  alignItems: "center",
},
duoPendingNameV2: {
  marginTop: 8,
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(12.8),
},
duoPendingConnectorV2: {
  width: "20%",
  alignItems: "center",
  justifyContent: "center",
},
duoPendingLineV2: {
  width: 2,
  height: 14,
  borderRadius: 2,
  backgroundColor: "rgba(255,255,255,0.14)",
},
duoPendingHintV2: {
  textAlign: "center",
  fontFamily: "Comfortaa_400Regular",
  fontSize: normalizeSize(12.6),
  lineHeight: normalizeSize(17),
  marginBottom: 12,
},
duoPendingActionsV2: {
  flexDirection: "row",
  gap: 10,
},
duoPendingPrimaryBtnV2: {
  flex: 1,
  height: 46,
  borderRadius: 16,
  overflow: "hidden",
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
  paddingHorizontal: 12,
},
duoPendingPrimaryBtnDisabledV2: {
  opacity: 0.92,
},
duoPendingPrimaryTextV2: {
  flex: 1,
  minWidth: 0,
  marginLeft: 10,
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(13.2),
  color: "#111",
},
duoPendingGhostBtnV2: {
  width: 118,
  height: 46,
  borderRadius: 16,
  overflow: "hidden",
  borderWidth: StyleSheet.hairlineWidth,
  borderColor: "rgba(255,255,255,0.14)",
  backgroundColor: "rgba(255,255,255,0.06)",
  alignItems: "center",
  justifyContent: "center",
},
duoPendingGhostInnerV2: {
  flexDirection: "row",
  alignItems: "center",
  gap: 8,
  paddingHorizontal: 10,
},
duoPendingGhostTextV2: {
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(12.8),
},
 imageContainer: {
    width: "100%",
    borderBottomLeftRadius: R.hero,
    borderBottomRightRadius: R.hero,
    overflow: "hidden",
    marginBottom: SPACING,
    ...S.float,
  },
avatarShell: {
  position: "relative",
  alignItems: "center",
  justifyContent: "center",
  overflow: "hidden",
  borderWidth: StyleSheet.hairlineWidth,
  ...S.card,
},
avatarRing: {
  position: "absolute",
  left: 0,
  right: 0,
  top: 0,
  bottom: 0,
  borderWidth: StyleSheet.hairlineWidth,
},
avatarSpecular: {
  position: "absolute",
  left: "10%",
  right: "10%",
  top: "8%",
  height: "42%",
  backgroundColor: "rgba(255,255,255,0.10)",
  transform: [{ skewY: "-10deg" }],
  opacity: 0.85,
},
avatarInitial: {
  fontFamily: "Comfortaa_700Bold",
  includeFontPadding: false,
},
avatarSheen: {
  position: "absolute",
  left: "10%",
  right: "10%",
  top: "10%",
  height: "42%",
  backgroundColor: "rgba(255,255,255,0.18)",
  transform: [{ skewY: "-10deg" }],
},
duoBarTrack: {
  height: 16, 
  borderRadius: 999,
  backgroundColor: Platform.OS === "android"
   ? "rgba(0,0,0,0.18)"
   : "rgba(255,255,255,0.10)",
  overflow: "hidden",
  borderWidth: 1,
  borderColor: "rgba(255,255,255,0.20)",
  position: "relative",
},
duoBarTrackSheen: {
  ...StyleSheet.absoluteFillObject,
  backgroundColor: "rgba(255,255,255,0.05)",
},
duoBarTicks: {
  ...StyleSheet.absoluteFillObject,
  flexDirection: "row",
  justifyContent: "space-evenly",
  alignItems: "center",
  opacity: 0.42, // ⬅️ plus visible
},
duoBarTick: {
  width: 1,
  height: "65%",
  borderRadius: 1,
  backgroundColor: Platform.OS === "android"
   ? "rgba(255,255,255,0.55)"
   : "rgba(255,255,255,0.30)",
},
duoBarFill: {
  height: "100%",
  borderRadius: 999,
},
duoBattleBar: {
  width: "100%",
  height: 18,
  borderRadius: 999,
  overflow: "hidden",
  borderWidth: 1,
  borderColor: "rgba(255,255,255,0.22)",
  backgroundColor: Platform.OS === "android"
   ? "rgba(0,0,0,0.12)"
   : "rgba(255,255,255,0.10)",
  position: "relative",
},
duoBattleRail: {
  ...StyleSheet.absoluteFillObject,
  opacity: 0.65,
  backgroundColor: Platform.OS === "android"
   ? "rgba(255,255,255,0.08)"
   : "rgba(255,255,255,0.04)",
},
duoBattleDivider: {
  position: "absolute",
  left: "50%",
  top: 1,
  bottom: 1,
  width: 3,
  borderRadius: 2,
  backgroundColor: "rgba(255,255,255,0.55)",
  shadowColor: "#000",
  shadowOpacity: 0.22,
  shadowRadius: 8,
  shadowOffset: { width: 0, height: 2 },
  elevation: 7,
  opacity: Platform.OS === "android" ? 0.9 : 0.55,
},
duoEliteWrap: {
  marginTop: SPACING * 1.6,
  alignItems: "center",
  width: "100%",
  paddingHorizontal: 12,
},
duoCrownMini: {
  position: "absolute",
  top: -10,
  right: -10,
  zIndex: 30,
},
duoCrownPill: {
  width: normalizeSize(26),
  height: normalizeSize(26),
  borderRadius: normalizeSize(13),
  alignItems: "center",
  justifyContent: "center",
  backgroundColor: "rgba(0,0,0,0.55)",
  borderWidth: 1,
  borderColor: "rgba(244, 211, 94, 0.38)",
  shadowColor: ACCENT.glow,
  shadowOpacity: 0.35,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 6 },
  elevation: 8,
},
duoCrownMiniEmoji: {
  fontSize: normalizeSize(14),
  includeFontPadding: false,
},
duoProgressStack: {
  width: "100%",
  maxWidth: 560,
  marginTop: 16,
  gap: 12,
},
duoBarRow: {
  width: "100%",
},
duoBarLabelRow: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  marginBottom: 6,
  gap: 10,
},
duoBarLabel: {
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(12),
  opacity: 0.9,
  flex: 1,
  minWidth: 0,
},
duoBarValue: {
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(12),
  opacity: 0.55,
  flexShrink: 0,
},
duoBarFillMe: {
  shadowColor: "#FF9F1C",
  shadowOpacity: 0.25,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 6 },
},
duoBarFillPartner: {
  shadowColor: "#00C2FF",
  shadowOpacity: 0.22,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 6 },
},
duoBattleLeft: {
  position: "absolute",
  left: 0,
  top: 0,
  bottom: 0,
  backgroundColor: "#FF9F1C",
  opacity: 0.85,
},
duoBattleRight: {
  position: "absolute",
  right: 0,
  top: 0,
  bottom: 0,
  backgroundColor: "#00C2FF",
  opacity: 0.85,
},
duoEliteAvatars: {
  width: "100%",
  maxWidth: 560,
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  gap: 12,
 paddingVertical: 10,
  paddingHorizontal: 12,
  borderRadius: 18,
  borderWidth: StyleSheet.hairlineWidth,
},
duoPendingRing: {
  position: "absolute",
   width: 38,
   height: 38,
   borderRadius: 999,
   borderWidth: 2.5,
   borderColor: "rgba(139,92,246,0.95)",
},
duoEliteCol: {
  alignItems: "center",
   flex: 1,
  minWidth: 0,
},
duoAvatarWrap: {
  position: "relative",
  alignItems: "center",
  justifyContent: "center",
},
duoEliteAvatar: {
  width: "100%",
  height: "100%",
  borderRadius: normalizeSize(37),
  borderWidth: 1.5,
  borderColor: "rgba(255,255,255,0.22)",
  backgroundColor: "rgba(255,255,255,0.08)",
  ...S.card,
},
duoEliteName: {
  marginTop: 8,
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(13),
  opacity: 0.92,
  maxWidth: "100%",
},
duoVsPill: {
  paddingHorizontal: 12,
  paddingVertical: 8,
  borderRadius: 999,
  borderWidth: 1,
},
duoVs: {
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(12),
  letterSpacing: 1.6,
  includeFontPadding: false,
},
duoAvatarShell: {
  position: "relative",
  width: normalizeSize(74),
  height: normalizeSize(74),
  borderRadius: normalizeSize(37),
  alignItems: "center",
  justifyContent: "center",
  backgroundColor: Platform.OS === "android"
  ? "rgba(255,255,255,0.10)"
  : "rgba(255,255,255,0.08)",
},
duoEliteStatus: {
  marginTop: 12,
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(18),
  opacity: 0.9,
  textAlign: "center",
  paddingHorizontal: 10,
},
duoEliteSubStatus: {
  marginTop: 4,
  fontFamily: "Comfortaa_400Regular",
  fontSize: normalizeSize(12),
  color: "rgba(255,255,255,0.72)",
  textAlign: "center",
  paddingHorizontal: 10,
},
actionsWrap: {
  marginTop: 24,
  paddingHorizontal: 16,
},
primaryActions: {
  gap: 12,
},
primaryBtn: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  paddingHorizontal: 18,
  height: 56,
  borderRadius: 18,
},
primaryBtnInvite: {
  backgroundColor: "#6366F1",
 borderWidth: 1,
 borderColor: "rgba(255,255,255,0.22)",
},
primaryBtnSecondary: {
  backgroundColor: "#fff",
  borderWidth: 1,
  borderColor: "rgba(0,0,0,0.12)",
},
primaryBtnText: {
  flex: 1,
  marginLeft: 12,
  fontSize: 16,
  fontFamily: "Comfortaa_700Bold",
  color: "#fff",
},
quickTextActive: {
  color: ACCENT.solid,
},
primaryBtnTextSecondary: {
  flex: 1,
  marginLeft: 12,
  fontSize: 16,
  fontFamily: "Comfortaa_700Bold",
  color: "#111",
},
duoAvatarFallback: {
  width: "100%",
  height: "100%",
  borderRadius: normalizeSize(37),
  alignItems: "center",
  justifyContent: "center",
  backgroundColor: Platform.OS === "android"
   ? "#FFFFFF"
   : "rgba(255,255,255,0.08)",
},
duoAvatarInitial: {
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(22),
  color: "rgba(255,255,255,0.92)",
  includeFontPadding: false,
},
duoAvatarRing: {
  position: "absolute",
  left: 0,
  top: 0,
  right: 0,
  bottom: 0,
  borderRadius: normalizeSize(37),
  borderWidth: 1,
  borderColor: "rgba(255,255,255,0.18)",
},
duoLeading: {
  color: ACCENT.solid,
},
duoBehind: {
  color: "#FF6B6B",
},
quickActions: {
  marginTop: 14,
  flexDirection: "row",
  flexWrap: "nowrap",          
  justifyContent: "space-between",
  gap: 10,                    
},
quickBtn: {
  flex: 1,                  
  minWidth: 0,                 
  alignItems: "center",
  justifyContent: "center",
  paddingVertical: 10,
  paddingHorizontal: 8,
  borderRadius: 14,
  minHeight: 56,             
  borderWidth: 1,
  borderColor: "rgba(0,0,0,0.12)",
  backgroundColor: "rgba(255,255,255,0.86)",
},
quickText: {
  width: "100%",
  textAlign: "center",
  flexShrink: 1,
  minWidth: 0,                 
  fontSize: normalizeSize(12.5),
  fontFamily: "Comfortaa_700Bold",
  includeFontPadding: false,
  lineHeight: normalizeSize(14),
},
quickBtnInner: {
  width: "100%",
  alignItems: "center",
  justifyContent: "center",
  gap: 6,
},
btnPressed: {
  transform: [{ scale: 0.98 }],
  opacity: 0.9,
},
  image: {
    width: "100%",
    backfaceVisibility: "hidden",
    borderBottomLeftRadius: R.hero,
    borderBottomRightRadius: R.hero,
  },
  loadingOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 9999,
    elevation: 9999,
    backgroundColor: "transparent",
    paddingHorizontal: 24,
  },
quickBtnDisabled: {
    opacity: 0.55,
  },
duoPendingMiniBadge: {
  position: "absolute",
  right: 6,
  bottom: 6,
  width: 18,
  height: 18,
  borderRadius: 9,
  alignItems: "center",
  justifyContent: "center",
  backgroundColor: "rgba(0,0,0,0.22)",
  borderWidth: StyleSheet.hairlineWidth,
  borderColor: "rgba(255,255,255,0.18)",
},
  loadingCard: {
    minWidth: 260,
    maxWidth: 320,
    borderRadius: R.card,
    paddingVertical: 18,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: GLASS.bgDark,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    ...S.float,
    overflow: "hidden",
  },
  loadingIconRing: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  loadingIconInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.55)",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingTextBlock: {
    alignItems: "center",
  },
heroVignette: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  loadingText: {
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  loadingSubText: {
    marginTop: 4,
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
backButtonContainer: {
    position: "absolute",
    top: 0,
    left: SPACING,
    zIndex: 50,        
    elevation: 50,
    pointerEvents: "box-none",
  },
  orb: {
  position: "absolute",
  opacity: 0.9,     
},
backButtonBlur: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: GLASS.border,
    backgroundColor: "rgba(0,0,0,0.16)",
    ...S.card,
  },
  backButtonPress: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  imagePlaceholder: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
scrollPad: { paddingBottom: SPACING },
  chipRow: {
  flexDirection: "row",
  flexWrap: "wrap",
  justifyContent: "center",
  marginTop: 6,
},
vsSide: {
  alignItems: "center",
  marginHorizontal: 24,
},
vsAvatarXL: {
  width: normalizeSize(120),
  height: normalizeSize(120),
  borderRadius: normalizeSize(60),
  borderWidth: 3,
  borderColor: ACCENT.solid,
  shadowColor: ACCENT.glow,
  shadowOpacity: 0.22,
  shadowRadius: 14,
  shadowOffset: { width: 0, height: 4 },
  elevation: 7,
},
vsModalRoot: {
  ...StyleSheet.absoluteFillObject,
  backgroundColor: "#000", // hard black base, then gradients on top
  justifyContent: "center",
  alignItems: "center",
  zIndex: 99999,
},
vsStage: {
  width: "100%",
  maxWidth: 820,
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
},
vsAvatarWrap: {
  position: "relative",
  alignItems: "center",
  justifyContent: "center",
},
vsGlowRing: {
  position: "absolute",
  width: normalizeSize(138),
  height: normalizeSize(138),
  borderRadius: normalizeSize(69),
  borderWidth: 2,
  borderColor: ACCENT.softBorder,
  shadowColor: ACCENT.glow,
  shadowOpacity: 0.26,
  shadowRadius: 18,
  shadowOffset: { width: 0, height: 6 },
  opacity: 0.85,
},
vsBadgeBig: {
  paddingVertical: 10,
  paddingHorizontal: 20,
  borderRadius: 999,
  shadowColor: "#000",
  shadowOpacity: 0.35,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 6 },
},
vsBadgeText: {
  color: "#000",
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(18),
  letterSpacing: 2,
},
vsNameXL: {
  color: "#fff",
  marginTop: 10,
  fontSize: normalizeSize(18),
  fontFamily: "Comfortaa_700Bold",
  textAlign: "center",
},
vsCenter: {
  marginHorizontal: 24,
},
chip: {
  flexDirection: "row",
  alignItems: "center",
  paddingVertical: 6,
  paddingHorizontal: 10,
  borderRadius: 999,
  borderWidth: 1,
  margin: 4, // remplace le gap du parent
},
chipDark: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderColor: "rgba(255,255,255,0.16)",
  },
  chipLight: {
    backgroundColor: "rgba(0,0,0,0.06)",
    borderColor: "rgba(0,0,0,0.08)",
  },
chipText: {
  fontFamily: "Comfortaa_700Bold",
  fontSize: normalizeSize(12),
  marginLeft: 6, // remplace le gap interne
  includeFontPadding: false,
},
  heroOverlay: {
  position: "absolute",
  left: 0,
  right: 0,
  bottom: 0,
  top: 0,
},
  avatarWrap: {
    width: normalizeSize(68),
    height: normalizeSize(68),
    borderRadius: normalizeSize(34),
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
    marginBottom: 6,
  },
  noImageText: {
    marginTop: SPACING,
    fontFamily: "Comfortaa_400Regular",
    fontSize: normalizeSize(16),
  },
  heroCardWrap: {
    width: "100%",
    paddingHorizontal: SPACING * 1.2,
    marginTop: -normalizeSize(26), // chevauche le hero (Keynote)
  },
  heroCardBlur: {
    borderRadius: R.card,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: GLASS.border,
    ...S.float,
  },
  heroCardInner: {
    borderRadius: R.card,
    paddingHorizontal: SPACING * 1.2,
    paddingTop: SPACING * 1.1,
    paddingBottom: SPACING * 1.25,
  },
  infoRecipeName: {
    fontSize: normalizeSize(28),
    marginTop: SPACING * 0.2,
    marginBottom: SPACING,
    textAlign: "center",
    fontFamily: "Comfortaa_700Bold",
  },
  category: {
    fontSize: normalizeSize(14),
    marginVertical: SPACING / 2,
    textAlign: "center",
    fontFamily: "Comfortaa_700Bold",
  },
progressSection: {
    alignItems: "center",       
    paddingHorizontal: SPACING,
    paddingTop: SPACING,
    width: "100%",             
   maxWidth: 560,
   alignSelf: "center",
  },
  takeChallengeButton: {
    borderRadius: R.btn,
    overflow: "hidden",
    marginTop: SPACING,
    ...S.card,
  },
  takeChallengeButtonGradient: {
    paddingVertical: SPACING,
    paddingHorizontal: SPACING * 2,
  },
  takeChallengeButtonText: {
    fontSize: normalizeSize(16),
    fontFamily: "Comfortaa_700Bold",
    textAlign: "center",
  },
  inProgressText: {
    fontSize: normalizeSize(16),
    marginTop: SPACING,
    fontFamily: "Comfortaa_700Bold",
    includeFontPadding: false,
  },
  markTodayButton: {
    borderRadius: R.btn,
    overflow: "hidden",
    marginTop: SPACING,
    ...S.card,
  },
  markTodayButtonGradient: {
    paddingVertical: SPACING,
    paddingHorizontal: SPACING * 2,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: R.btn,
  },
  markTodayButtonText: {
    fontSize: normalizeSize(16),
    fontFamily: "Comfortaa_700Bold",
  },
  progressText: {
    fontSize: normalizeSize(14),
    marginBottom: SPACING,
    textAlign: "center",
    marginTop: SPACING / 2,
    fontFamily: "Comfortaa_400Regular",
  },
  progressBarBackground: {
  position: "relative",
    width: "100%",       
    maxWidth: 480,        
    minWidth: 220,
    alignSelf: "center",
    zIndex: 0,
    height: normalizeSize(10),
    borderRadius: normalizeSize(5),
    overflow: "hidden",
    marginTop: SPACING,
    backgroundColor: "rgba(255,255,255,0.10)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
  },
  progressBarFill: {
    height: "100%",
  },
  infoDescriptionRecipe: {
    textAlign: "center",
    fontSize: normalizeSize(16),
    includeFontPadding: false,
    marginTop: SPACING * 2,
    marginHorizontal: SPACING,
    lineHeight: normalizeSize(22),
    fontFamily: "Comfortaa_400Regular",
  },
});